### ISSUE TITLE
No sound in apps on early 1K Vita

### ISSUE THREAD

**Issue by GrapheneCt** [cuevavirus/MusicPremium#1]
No sound is played back in apps on early 1K Vita model. On 2K model with the same set of other plugins everything works fine. 

Maybe because of the different DAC IC used in early Vita models?

**Comment by cuevavirus** [comment]
I don't have an early 1000 model to test with but with a later 1000 model everything also works fine. Is there no sound in all games and apps or are you referring to system apps like settings and photos?

**Comment by GrapheneCt** [comment]
No. Only games that call sceAppMgrAcquireBgmPort are affected. Shell music playback is now possible in them, but all in-game audio is missing.

Huh, it's even worse than I thought. While in Death Mark sound just disappeare, Thomas Was Alone crashes at startup with C2-12828-1 error.

**Comment by cuevavirus** [comment]
Can you try the new 1.0.1 release?

I was able to reproduce the crash with Thomas Was Alone and at least that is fixed.

**Comment by GrapheneCt** [comment]
Works fine now. However, I found another issue (exists both in 1.0.0 and 1.0.1): no sound in pspemu when music playback is active. If music is paused, sound appears after few seconds.

**Comment by cuevavirus** [comment]
Thank you for your help. Please open a separate issue about the pspemu sound.
