### ISSUE TITLE
adrenaline bubble manager not working when use plugin music !

### ISSUE THREAD

**Issue by kokamidavid** [cuevavirus/MusicPremium#3]
I install MusicPremium 1.02 on my psvita, plugin no issue for psvita game and RetroArch game, but when i play ps1 game in adrealine bubble manager ( bubble icon on main menu vita ) >game ps1 not play and  black screen. However this plugin is awesome, thanks you !

**Comment by cuevavirus** [comment]
Fixed in latest release.
