### ISSUE TITLE
NAX Music player

### ISSUE THREAD

**Issue by dkrmdi** [cuevavirus/MusicPremium#5]
Can you also make NAX music player play in the background or while the screen is off?

Thank you.

**Comment by cuevavirus** [comment]
Sure

**Comment by cuevavirus** [comment]
It already doesn't play in the background or with screen off so nothing i can do about that.

**Comment by dkrmdi** [comment]
Okay. Thank you.

**Comment by dkrmdi** [comment]
Would it be possible to control the music app with buttons while the screen is off?

Like go to next track or previous track using L R buttons. Stop or resume playback using o/x button, or fastforward using the d-pad all while the screen is off.
