### ISSUE TITLE
Delted everyhting

### ISSUE THREAD

**Issue by Mpalasz** [cuevavirus/MusicPremium#6]
So i installed this @@@@@ plugin trough autoplugin and it fk@@ deleted everything in my ps vita including sd2vita plugin so i cant use my ps vita anymore i need someone to take blame and responsibility for this stupid plugin

**Comment by cuevavirus** [comment]
report this problem to autoplugin

**Comment by teakhanirons** [comment]
@Mpalasz https://www.reddit.com/r/vitahacks/comments/g1vowq

**Comment by Mpalasz** [comment]
@teakhanirons thank you so now what they messed up my whole system and sorry for blaming the owner of the plugin but they messed up my enso ps vita

**Comment by teakhanirons** [comment]
@Mpalasz read the link, it tells you how to restore

**Comment by Mpalasz** [comment]
@teakhanirons i get an error when i go to the hankaku page saying error: Cant find variable:found

**Comment by teakhanirons** [comment]
@Mpalasz that's off topic, please go to henkaku discord or vitahacks discord for help

**Comment by Mpalasz** [comment]
@teakhanirons i am on 3.65 but because of sd2vita i cant launch h encore do you have any solutions?

**Comment by Cimmerian-Iter** [comment]
Follow the 3.65 part and not the 3.60 it's clearly indicated in the post

**Comment by Mpalasz** [comment]
@Cimmerian-Iter so what part of the h encore wont launch didnt you understand?i clearly said that h encore app wont launch and it keeps saying open the app from the memory stick it is installed from but i didnt  change memories and i use sd2vita

**Comment by Cimmerian-Iter** [comment]
You don't use the sd2vita anymore youre on he memorycard now.

Open hencore and hold R during the process (or L I don't remember)

**Comment by Mpalasz** [comment]
@Cimmerian-Iter bro i managed to get the s2vita working again just buy reinstalling sd2vita plugin that easy but the h encore doesnt work anymore its like i am not having henkaku in the settings i dont even have the henkaku settings and thats pretty bad but i still have cfw how is tha possbile

**Comment by Cimmerian-Iter** [comment]
this is possible because henkaku (the hen) is till alive. Loaded by enso

hencore is just here to launch henkaku nothing more.

And enso load henkaku


What you need tho is to reset taihen.

Also this is certainly the best occasion for you to downgrade to 3.60 to avoid this in the future so I would like you to downgrade to 3.60

**Comment by Mpalasz** [comment]
@Cimmerian-Iter so ijust reinstalled henkaku in my ps vita and pressed reset taihen but nothing seemed to change
and now my ps vita is broke again

**Comment by Mpalasz** [comment]
@Cimmerian-Iter hell yeah i managed to fix it btw thanks for bothering to help me <3

**Comment by Cimmerian-Iter** [comment]
You're welcome but next time please avoid being rude to devs. Bug can happen

**Comment by teakhanirons** [comment]
S-so we don't need to take blame and responsibility for this stupid plugin because he installed this @@@@@ plugin trough autoplugin and it fk@@ deleted everything in his ps vita including sd2vita plugin so he couldnt use his ps vita anymore???? WOW THANKS SAMI!!!!!

**Comment by Cimmerian-Iter** [comment]
And then I wonder how TF you're able to call yourself a dev

**Comment by teakhanirons** [comment]
At least I haven't bricked all my Vitas

**Comment by teakhanirons** [comment]
WELL KNOWN VITA BRICKER/HELPER ADMITS TO BRICKING VITAS FOR FUN!!!

I don't call myself a dev, I call myself a string editor.
